version: '3'
services:
  graphite:
    image: graphiteapp/graphite-statsd
    ports:
      - "8082:80"       # Graphite web UI
      - "2003-2004:2003-2004"
      - "8125:8125/udp"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"     # Grafana UI
